export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const MOSTRAR_BOTONES = 'MOSTRAR_BOTONES';
export const SELECCIONAR_ACTUAL = 'SELECCIONAR_ACTUAL';
export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const MOSTRAR_CARDS = 'MOSTRAR_CARDS';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const REINICIAR_FORMULARIO = 'REINICIAR_FORMULARIO';